product_controllers:
    resource: ../../src/Component/ProductFrontEnd/Communication/
    type: annotation

user_controllers:
    resource: ../../src/Component/User/Communication/
    type: annotation

category_controllers:
    resource: ../../src/Component/Category/Communication/
    type: annotation